export const AppRoutes = {
  home: "/",
  login: "/login",
  signUp: "/sign-up",
  dashboard: "/account/dashboard",
  ecoStory: "/account/myecostory",
  settings: "/account/settings",
  envIssues: "/environmental_issues",
  sustainableLiving: "/sustainable_living",
  missionTeam: "/mission_and_team",
  pressAndMedia: "/press_and_media",
  forum: "/forum",
  forumPost: "/post/:postId",
  notImplemented: "/not_implemented",
  submitUserStory: "/submit_user_story",
  userStories: "/user_stories",
};
